name: PR Preview to GitHub Pages

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      pages: write
      id-token: write

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1

      - name: Copy files to preview folder
        run: |
          mkdir -p preview/pr-${{ github.event.pull_request.number }}
          # Copy all files except .git, .github, and preview directories
          rsync -av --exclude='.git*' --exclude='preview' . preview/pr-${{ github.event.pull_request.number }}/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./preview/pr-${{ github.event.pull_request.number }}
          publish_branch: gh-pages
          destination_dir: pr-preview/pr-${{ github.event.pull_request.number }}
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Get GitHub Pages URL
        id: pages
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const response = await github.rest.repos.getPages({ 
              owner: context.repo.owner, 
              repo: context.repo.repo 
            });
            return response.data.html_url;

      - name: Comment PR with preview URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: preview-url
          message: |
            🚀 **PR Preview Deployed!**
            
            Your preview is available at: 
            **${{ steps.pages.outputs.result }}pr-preview/pr-${{ github.event.pull_request.number }}/**
            
            Changes will be reflected automatically when you push new commits to this PR.
